// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckInstanceModUpdates(arg1, arg2) {
  return window['go']['app']['App']['CheckInstanceModUpdates'](arg1, arg2);
}

export function CheckModUpdates() {
  return window['go']['app']['App']['CheckModUpdates']();
}

export function CheckUpdate() {
  return window['go']['app']['App']['CheckUpdate']();
}

export function ExitGame() {
  return window['go']['app']['App']['ExitGame']();
}

export function GetAuthStatus() {
  return window['go']['app']['App']['GetAuthStatus']();
}

export function GetConfig() {
  return window['go']['app']['App']['GetConfig']();
}

export function GetCrashReports() {
  return window['go']['app']['App']['GetCrashReports']();
}

export function GetGameLogs() {
  return window['go']['app']['App']['GetGameLogs']();
}

export function GetInstalledMods() {
  return window['go']['app']['App']['GetInstalledMods']();
}

export function GetInstanceInstalledMods(arg1, arg2) {
  return window['go']['app']['App']['GetInstanceInstalledMods'](arg1, arg2);
}

export function GetLauncherVersion() {
  return window['go']['app']['App']['GetLauncherVersion']();
}

export function GetLogs() {
  return window['go']['app']['App']['GetLogs']();
}

export function GetModCategories() {
  return window['go']['app']['App']['GetModCategories']();
}

export function GetModDetails(arg1) {
  return window['go']['app']['App']['GetModDetails'](arg1);
}

export function GetModFiles(arg1) {
  return window['go']['app']['App']['GetModFiles'](arg1);
}

export function GetMusicEnabled() {
  return window['go']['app']['App']['GetMusicEnabled']();
}

export function GetNews(arg1) {
  return window['go']['app']['App']['GetNews'](arg1);
}

export function GetNick() {
  return window['go']['app']['App']['GetNick']();
}

export function GetPlatformInfo() {
  return window['go']['app']['App']['GetPlatformInfo']();
}

export function GetUserProfile() {
  return window['go']['app']['App']['GetUserProfile']();
}

export function GetUserUUID() {
  return window['go']['app']['App']['GetUserUUID']();
}

export function InstallMod(arg1) {
  return window['go']['app']['App']['InstallMod'](arg1);
}

export function InstallModFile(arg1, arg2) {
  return window['go']['app']['App']['InstallModFile'](arg1, arg2);
}

export function InstallModFileToInstance(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['InstallModFileToInstance'](arg1, arg2, arg3, arg4);
}

export function InstallModToInstance(arg1, arg2, arg3) {
  return window['go']['app']['App']['InstallModToInstance'](arg1, arg2, arg3);
}

export function IsGameRunning() {
  return window['go']['app']['App']['IsGameRunning']();
}

export function Launch(arg1) {
  return window['go']['app']['App']['Launch'](arg1);
}

export function LoginWithHytaleAccount() {
  return window['go']['app']['App']['LoginWithHytaleAccount']();
}

export function LogoutHytaleAccount() {
  return window['go']['app']['App']['LogoutHytaleAccount']();
}

export function OpenAuthURL(arg1) {
  return window['go']['app']['App']['OpenAuthURL'](arg1);
}

export function OpenGameFolder() {
  return window['go']['app']['App']['OpenGameFolder']();
}

export function OpenInstanceModsFolder(arg1, arg2) {
  return window['go']['app']['App']['OpenInstanceModsFolder'](arg1, arg2);
}

export function OpenModsFolder() {
  return window['go']['app']['App']['OpenModsFolder']();
}

export function QuickLaunch() {
  return window['go']['app']['App']['QuickLaunch']();
}

export function RunDiagnostics() {
  return window['go']['app']['App']['RunDiagnostics']();
}

export function SaveConfig() {
  return window['go']['app']['App']['SaveConfig']();
}

export function SaveDiagnosticReport() {
  return window['go']['app']['App']['SaveDiagnosticReport']();
}

export function SearchMods(arg1, arg2, arg3) {
  return window['go']['app']['App']['SearchMods'](arg1, arg2, arg3);
}

export function SelectGameInstallDirectory() {
  return window['go']['app']['App']['SelectGameInstallDirectory']();
}

export function SelectInstanceDirectory() {
  return window['go']['app']['App']['SelectInstanceDirectory']();
}

export function SetMusicEnabled(arg1) {
  return window['go']['app']['App']['SetMusicEnabled'](arg1);
}

export function SetNick(arg1) {
  return window['go']['app']['App']['SetNick'](arg1);
}

export function ToggleInstanceMod(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ToggleInstanceMod'](arg1, arg2, arg3, arg4);
}

export function ToggleMod(arg1, arg2) {
  return window['go']['app']['App']['ToggleMod'](arg1, arg2);
}

export function UninstallInstanceMod(arg1, arg2, arg3) {
  return window['go']['app']['App']['UninstallInstanceMod'](arg1, arg2, arg3);
}

export function UninstallMod(arg1) {
  return window['go']['app']['App']['UninstallMod'](arg1);
}

export function Update() {
  return window['go']['app']['App']['Update']();
}
