// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mods} from '../models';
import {updater} from '../models';
import {config} from '../models';
import {app} from '../models';
import {news} from '../models';

export function CheckInstanceModUpdates(arg1:string,arg2:number):Promise<Array<mods.Mod>>;

export function CheckModUpdates():Promise<Array<mods.Mod>>;

export function CheckUpdate():Promise<updater.Asset>;

export function ExitGame():Promise<void>;

export function GetAuthStatus():Promise<Record<string, any>>;

export function GetConfig():Promise<config.Config>;

export function GetCrashReports():Promise<Array<app.CrashReport>>;

export function GetGameLogs():Promise<string>;

export function GetInstalledMods():Promise<Array<mods.Mod>>;

export function GetInstanceInstalledMods(arg1:string,arg2:number):Promise<Array<mods.Mod>>;

export function GetLauncherVersion():Promise<string>;

export function GetLogs():Promise<string>;

export function GetModCategories():Promise<Array<mods.ModCategory>>;

export function GetModDetails(arg1:number):Promise<mods.CurseForgeMod>;

export function GetModFiles(arg1:number):Promise<Array<mods.ModFile>>;

export function GetMusicEnabled():Promise<boolean>;

export function GetNews(arg1:number):Promise<Array<news.NewsItem>>;

export function GetNick():Promise<string>;

export function GetPlatformInfo():Promise<Record<string, string>>;

export function GetUserProfile():Promise<Record<string, string>>;

export function GetUserUUID():Promise<string>;

export function InstallMod(arg1:number):Promise<void>;

export function InstallModFile(arg1:number,arg2:number):Promise<void>;

export function InstallModFileToInstance(arg1:number,arg2:number,arg3:string,arg4:number):Promise<void>;

export function InstallModToInstance(arg1:number,arg2:string,arg3:number):Promise<void>;

export function IsGameRunning():Promise<boolean>;

export function Launch(arg1:string):Promise<void>;

export function LoginWithHytaleAccount():Promise<void>;

export function LogoutHytaleAccount():Promise<void>;

export function OpenAuthURL(arg1:string):Promise<void>;

export function OpenGameFolder():Promise<void>;

export function OpenInstanceModsFolder(arg1:string,arg2:number):Promise<void>;

export function OpenModsFolder():Promise<void>;

export function QuickLaunch():Promise<void>;

export function RunDiagnostics():Promise<app.DiagnosticReport>;

export function SaveConfig():Promise<void>;

export function SaveDiagnosticReport():Promise<string>;

export function SearchMods(arg1:string,arg2:number,arg3:number):Promise<mods.SearchResult>;

export function SelectGameInstallDirectory():Promise<string>;

export function SelectInstanceDirectory():Promise<string>;

export function SetMusicEnabled(arg1:boolean):Promise<void>;

export function SetNick(arg1:string):Promise<void>;

export function ToggleInstanceMod(arg1:string,arg2:boolean,arg3:string,arg4:number):Promise<void>;

export function ToggleMod(arg1:string,arg2:boolean):Promise<void>;

export function UninstallInstanceMod(arg1:string,arg2:string,arg3:number):Promise<void>;

export function UninstallMod(arg1:string):Promise<void>;

export function Update():Promise<void>;
